
row_wise_input_file = 'risk_data.csv'
column_wise_input_file = 'risk_data_column_wise.csv'

install:
	pip install --upgrade pip &&\
		pip install -r requirements.txt

test:
	python -m pytest -vv test_hello.py

format:
	black *.py

lint:
	pylint --disable=R,C hello.py

hello:
	echo "Hello, world!"

run-row-wise:
	python monte_carlo_planner/app/row_wise_runner.py $(row_wise_input_file)

run-column-wise:
	python monte_carlo_planner/app/column_wise_runner.py $(column_wise_input_file)

all: install lint test

